### PR TITLE
Hungarian translation

### PR DESCRIPTION
**Pull request by wouldhide**
### Summary
Adds hungarian (hu_HU) translation with 'hu' language key

### Checklist

- [x] Added a changelog entry
- [x] Ran unit tests

### CODE REVIEW

**Comment by gabor-boros** [comment]
👍 I would be very happy to see this in production

**Comment by crookedneighbor** [comment]
Thanks for the PR, we'll have our translation look at it sometime this week.

**Comment by lilaconlee** [comment]
Because Hungarian is not supported in our PayPal flows, we've opted to not support this as an official translation but as part of [1.3.0](https://github.com/braintree/braintree-web-drop-in/blob/master/CHANGELOG.md#130) you can supply your own translations when creating Drop-in. See our [reference documentation](https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#.create) for an example.

**Comment by crookedneighbor** [comment]
This locale has been added in v1.25.0

**Pull request closed without merging**
