### PR TITLE
Add Arabic translation

### PR DESCRIPTION
**Pull request by Tantawi**
I have added Arabic translation. It is standard Arabic that is applicable in all Arabic speaking countries, but since I had to choose a specific locale, I chose ar_EG (Egypt).

I have also modified the gitignore file to ignore IntelliJ IDEA's configuration files, as I will probably be contributing more for Arabic language support.

Thank you!

### CODE REVIEW

**Comment by Tantawi** [comment]
I closed it by mistake, sorry! Re-opened.

**Comment by crookedneighbor** [comment]
Currently, we can only officially support languages that the PayPal flow supports. 

However, you can supply your own translations when creating Drop-in. See our [reference documentation](https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#create-examples) for an example of passing a translations object into your create call. Look for the example with the caption `Use your own translations`

**Comment by Tantawi** [comment]
Alright, thanks.

**Comment by crookedneighbor** [comment]
This locale has been added in v1.25.0

**Pull request closed without merging**
